apiVersion: v1
kind: ConfigMap
metadata:
  name: filter-local-ratelimit-cm
  namespace: default
data:
  envoy.yaml.tmpl: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 127.0.0.1
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.filters.http.adaptive_concurrency
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.adaptive_concurrency.v3.AdaptiveConcurrency
            gradient_controller_config:
              sample_aggregate_percentile:
                value: 1
            concurrency_limit_params:
              concurrency_update_interval: 0.1s
            min_rtt_calc_params:
              jitter:
                value: 10
              interval: 60s
              request_count: 50
          enabled:
            default_value: true
            runtime_key: "adaptive_concurrency.enabled"