apiVersion: v1
kind: ConfigMap
metadata:
  name: filter-local-ratelimit-cm
  namespace: default
data:
  envoy.yaml.tmpl: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 127.0.0.1
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            http_filters:
            - name: envoy.filters.http.local_ratelimit
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                stat_prefix: http_local_rate_limiter
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match: { prefix: "/" }
                  route:
                    rate_limits:
                    - actions:
                      - request_headers:
                          header_name: ":path"
                          descriptor_key: path
                  typed_per_filter_config:
                    envoy.filters.http.local_ratelimit:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                      stat_prefix: test
                      token_bucket:
                        max_tokens: 1
                        tokens_per_fill: 1
                        fill_interval: 1800s
                      filter_enabled:
                        runtime_key: test_enabled
                        default_value:
                          numerator: 100
                          denominator: HUNDRED
                      filter_enforced:
                        runtime_key: test_enforced
                        default_value:
                          numerator: 100
                          denominator: HUNDRED
                      descriptors:
                      - key: PATH
                        value: "/productpage"
                        rate_limit:
                          unit: hour
                          requests_per_unit: 1